/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef unsigned int uint32_t;
//GPIO
#define GPIOA_BASE 	0x40010800
#define GPIOA_CRL  *(volatile uint32_t*)(GPIOA_BASE + 0x00)
#define GPIOA_CRH  *(volatile uint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR  *(volatile uint32_t*)(GPIOA_BASE + 0x0C)

//RCC
#define RCC_BASE 		0x40021000
#define RCC_APB2ENR  *(volatile uint32_t*)(RCC_BASE + 0x18)

//EXTI
#define EXTI_BASE 		0x40010400
#define EXTI_IMR  	*(volatile uint32_t*)(EXTI_BASE + 0x00)
#define EXTI_RTSR  	*(volatile uint32_t*)(EXTI_BASE + 0x08)
#define EXTI_PR  	*(volatile uint32_t*)(EXTI_BASE + 0x14)

//AFIO
#define AFIO_BASE 		0x40010000
#define AFIO_EXTICR1  	*(volatile uint32_t*)(AFIO_BASE + 0x08)

//NVIC
#define NVIC_ISER0  	*(volatile uint32_t*)(0xE000E100)


void EXTI_init(void){
	//Map PORTA-PIN0----->EXTI
	AFIO_EXTICR1 = 0;
	//RISING EDGE DETECTION
	EXTI_RTSR |= (1<<0);
	//MASK PIN 0
	EXTI_IMR |= (1<<0);
	//NVIC MASK
	NVIC_ISER0 |= (1<<6);
}

void GPIO_init(void){
	//Alternate function output Push-pull
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	//Floating input (reset state)
	GPIOA_CRL |= (1<<2);
}

void RCC_init(void){
	//Enable clock for EXTI
	RCC_APB2ENR |= (1<<0);
	//Enable clock for GPIOA
	RCC_APB2ENR |= (1<<2);
}

int main(void)
{
	RCC_init();
	GPIO_init();
	EXTI_init();
	for(;;);
}

void EXTI0_IRQHandler(void){
	// Toggle LED on pin 13
	GPIOA_ODR ^= (1<<13) ;

	// Clear pending status of EXTI0
	EXTI_PR |= (1<<0);
}
